/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const BookPatientRequest = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'refDoctor' : IDL.Text,
  'gender' : Gender,
  'testIds' : IDL.Vec(IDL.Nat),
  'mobile' : IDL.Text,
});
export const SampleStatus = IDL.Variant({
  'sampleReceived' : IDL.Null,
  'sampleCollected' : IDL.Null,
  'reportReady' : IDL.Null,
  'processing' : IDL.Null,
});
export const PatientPublic = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'status' : SampleStatus,
  'name' : IDL.Text,
  'refDoctor' : IDL.Text,
  'centerId' : IDL.Text,
  'bookingDate' : IDL.Int,
  'gender' : Gender,
  'testIds' : IDL.Vec(IDL.Nat),
  'mobile' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const PaymentPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'date' : IDL.Int,
  'invoiceNumber' : IDL.Text,
  'centerId' : IDL.Text,
  'notes' : IDL.Text,
  'amount' : IDL.Nat,
});
export const BillingStats = IDL.Record({
  'totalTests' : IDL.Nat,
  'totalCommission' : IDL.Nat,
  'lastPayment' : IDL.Opt(PaymentPublic),
});
export const CenterStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const CollectionCenterPublic = IDL.Record({
  'id' : IDL.Text,
  'status' : CenterStatus,
  'ownerName' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'todaysSamples' : IDL.Nat,
  'pendingReports' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'thisMonthRevenue' : IDL.Nat,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'reportUrl' : IDL.Text,
  'patientId' : IDL.Text,
  'filename' : IDL.Text,
  'centerId' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const LabTest = IDL.Record({
  'id' : IDL.Nat,
  'mrpPrice' : IDL.Nat,
  'fastingRequired' : IDL.Bool,
  'name' : IDL.Text,
  'sampleType' : IDL.Text,
  'tubeType' : IDL.Text,
  'reportTime' : IDL.Text,
  'category' : IDL.Text,
  'partnerPrice' : IDL.Nat,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'collectionCenter' : IDL.Null,
});
export const Session = IDL.Record({
  'token' : IDL.Text,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
});
export const LoginResult = IDL.Variant({ 'ok' : Session, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addCenter' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'addPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'bookPatient' : IDL.Func([IDL.Text, BookPatientRequest], [IDL.Text], []),
  'deleteTest' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'getAllPatients' : IDL.Func([IDL.Text], [IDL.Vec(PatientPublic)], ['query']),
  'getBillingStats' : IDL.Func([IDL.Text, IDL.Text], [BillingStats], ['query']),
  'getCenterById' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(CollectionCenterPublic)],
      ['query'],
    ),
  'getCenters' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CollectionCenterPublic)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([IDL.Text], [DashboardStats], ['query']),
  'getMyCenter' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CollectionCenterPublic)],
      ['query'],
    ),
  'getPatientByIdOrMobile' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(PatientPublic)],
      ['query'],
    ),
  'getPatientsByCenter' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PatientPublic)],
      ['query'],
    ),
  'getPaymentsByCenter' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(PaymentPublic)],
      ['query'],
    ),
  'getReportsByCenter' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
      [IDL.Vec(Report)],
      ['query'],
    ),
  'getReportsByPatient' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Report)],
      ['query'],
    ),
  'getTestById' : IDL.Func([IDL.Nat], [IDL.Opt(LabTest)], ['query']),
  'getTests' : IDL.Func([], [IDL.Vec(LabTest)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'logout' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'markPaymentPaid' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'setCenterStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Bool], []),
  'updateCenter' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateSampleStatus' : IDL.Func(
      [IDL.Text, IDL.Text, SampleStatus],
      [IDL.Opt(PatientPublic)],
      [],
    ),
  'updateTest' : IDL.Func([IDL.Text, LabTest], [IDL.Bool], []),
  'uploadReport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Opt(Session)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const BookPatientRequest = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'refDoctor' : IDL.Text,
    'gender' : Gender,
    'testIds' : IDL.Vec(IDL.Nat),
    'mobile' : IDL.Text,
  });
  const SampleStatus = IDL.Variant({
    'sampleReceived' : IDL.Null,
    'sampleCollected' : IDL.Null,
    'reportReady' : IDL.Null,
    'processing' : IDL.Null,
  });
  const PatientPublic = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'status' : SampleStatus,
    'name' : IDL.Text,
    'refDoctor' : IDL.Text,
    'centerId' : IDL.Text,
    'bookingDate' : IDL.Int,
    'gender' : Gender,
    'testIds' : IDL.Vec(IDL.Nat),
    'mobile' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const PaymentPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'date' : IDL.Int,
    'invoiceNumber' : IDL.Text,
    'centerId' : IDL.Text,
    'notes' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const BillingStats = IDL.Record({
    'totalTests' : IDL.Nat,
    'totalCommission' : IDL.Nat,
    'lastPayment' : IDL.Opt(PaymentPublic),
  });
  const CenterStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const CollectionCenterPublic = IDL.Record({
    'id' : IDL.Text,
    'status' : CenterStatus,
    'ownerName' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'todaysSamples' : IDL.Nat,
    'pendingReports' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'thisMonthRevenue' : IDL.Nat,
  });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'reportUrl' : IDL.Text,
    'patientId' : IDL.Text,
    'filename' : IDL.Text,
    'centerId' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const LabTest = IDL.Record({
    'id' : IDL.Nat,
    'mrpPrice' : IDL.Nat,
    'fastingRequired' : IDL.Bool,
    'name' : IDL.Text,
    'sampleType' : IDL.Text,
    'tubeType' : IDL.Text,
    'reportTime' : IDL.Text,
    'category' : IDL.Text,
    'partnerPrice' : IDL.Nat,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'collectionCenter' : IDL.Null,
  });
  const Session = IDL.Record({
    'token' : IDL.Text,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
  });
  const LoginResult = IDL.Variant({ 'ok' : Session, 'err' : IDL.Text });
  
  return IDL.Service({
    'addCenter' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'addPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'bookPatient' : IDL.Func([IDL.Text, BookPatientRequest], [IDL.Text], []),
    'deleteTest' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'getAllPatients' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PatientPublic)],
        ['query'],
      ),
    'getBillingStats' : IDL.Func(
        [IDL.Text, IDL.Text],
        [BillingStats],
        ['query'],
      ),
    'getCenterById' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(CollectionCenterPublic)],
        ['query'],
      ),
    'getCenters' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CollectionCenterPublic)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([IDL.Text], [DashboardStats], ['query']),
    'getMyCenter' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CollectionCenterPublic)],
        ['query'],
      ),
    'getPatientByIdOrMobile' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(PatientPublic)],
        ['query'],
      ),
    'getPatientsByCenter' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PatientPublic)],
        ['query'],
      ),
    'getPaymentsByCenter' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(PaymentPublic)],
        ['query'],
      ),
    'getReportsByCenter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
        [IDL.Vec(Report)],
        ['query'],
      ),
    'getReportsByPatient' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Report)],
        ['query'],
      ),
    'getTestById' : IDL.Func([IDL.Nat], [IDL.Opt(LabTest)], ['query']),
    'getTests' : IDL.Func([], [IDL.Vec(LabTest)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'logout' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'markPaymentPaid' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'setCenterStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateCenter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateSampleStatus' : IDL.Func(
        [IDL.Text, IDL.Text, SampleStatus],
        [IDL.Opt(PatientPublic)],
        [],
      ),
    'updateTest' : IDL.Func([IDL.Text, LabTest], [IDL.Bool], []),
    'uploadReport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Opt(Session)], []),
  });
};

export const init = ({ IDL }) => { return []; };