/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillingStats {
  'totalTests' : bigint,
  'totalCommission' : bigint,
  'lastPayment' : [] | [PaymentPublic],
}
export interface BookPatientRequest {
  'age' : bigint,
  'name' : string,
  'refDoctor' : string,
  'gender' : Gender,
  'testIds' : Array<bigint>,
  'mobile' : string,
}
export type CenterStatus = { 'active' : null } |
  { 'inactive' : null };
export interface CollectionCenterPublic {
  'id' : string,
  'status' : CenterStatus,
  'ownerName' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface LabTest {
  'id' : bigint,
  'mrpPrice' : bigint,
  'fastingRequired' : boolean,
  'name' : string,
  'sampleType' : string,
  'tubeType' : string,
  'reportTime' : string,
  'category' : string,
  'partnerPrice' : bigint,
}
export type LoginResult = { 'ok' : Session } |
  { 'err' : string };
export interface PatientPublic {
  'id' : string,
  'age' : bigint,
  'status' : SampleStatus,
  'name' : string,
  'refDoctor' : string,
  'centerId' : string,
  'bookingDate' : bigint,
  'gender' : Gender,
  'testIds' : Array<bigint>,
  'mobile' : string,
}
export interface PaymentPublic {
  'id' : bigint,
  'status' : PaymentStatus,
  'date' : bigint,
  'invoiceNumber' : string,
  'centerId' : string,
  'notes' : string,
  'amount' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null };
export interface Report {
  'id' : bigint,
  'reportUrl' : string,
  'patientId' : string,
  'filename' : string,
  'centerId' : string,
  'uploadedAt' : bigint,
}
export type Role = { 'admin' : null } |
  { 'collectionCenter' : null };
export type SampleStatus = { 'sampleReceived' : null } |
  { 'sampleCollected' : null } |
  { 'reportReady' : null } |
  { 'processing' : null };
export interface Session {
  'token' : string,
  'userId' : string,
  'createdAt' : bigint,
  'role' : Role,
}
export interface _SERVICE {
  'addCenter' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    boolean
  >,
  'addPayment' : ActorMethod<[string, string, bigint, string, string], bigint>,
  'addTest' : ActorMethod<
    [string, string, string, string, string, boolean, string, bigint, bigint],
    bigint
  >,
  'bookPatient' : ActorMethod<[string, BookPatientRequest], string>,
  'deleteTest' : ActorMethod<[string, bigint], boolean>,
  'getBillingStats' : ActorMethod<[string, string], BillingStats>,
  'getCenterById' : ActorMethod<
    [string, string],
    [] | [CollectionCenterPublic]
  >,
  'getCenters' : ActorMethod<[string], Array<CollectionCenterPublic>>,
  'getMyCenter' : ActorMethod<[string], [] | [CollectionCenterPublic]>,
  'getPatientByIdOrMobile' : ActorMethod<
    [string, string],
    [] | [PatientPublic]
  >,
  'getPatientsByCenter' : ActorMethod<[string], Array<PatientPublic>>,
  'getPaymentsByCenter' : ActorMethod<[string, string], Array<PaymentPublic>>,
  'getReportsByCenter' : ActorMethod<
    [string, string, [] | [bigint], [] | [bigint]],
    Array<Report>
  >,
  'getReportsByPatient' : ActorMethod<[string, string], Array<Report>>,
  'getTestById' : ActorMethod<[bigint], [] | [LabTest]>,
  'getTests' : ActorMethod<[], Array<LabTest>>,
  'login' : ActorMethod<[string, string], LoginResult>,
  'logout' : ActorMethod<[string], boolean>,
  'markPaymentPaid' : ActorMethod<[string, bigint], boolean>,
  'setCenterStatus' : ActorMethod<[string, string, boolean], boolean>,
  'updateCenter' : ActorMethod<
    [string, string, string, string, string, string, string],
    boolean
  >,
  'updateSampleStatus' : ActorMethod<
    [string, string, SampleStatus],
    [] | [PatientPublic]
  >,
  'updateTest' : ActorMethod<[string, LabTest], boolean>,
  'uploadReport' : ActorMethod<[string, string, string, string], bigint>,
  'validateSession' : ActorMethod<[string], [] | [Session]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];