/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BookPatientRequest {
    age: bigint;
    name: string;
    refDoctor: string;
    gender: Gender;
    testIds: Array<bigint>;
    mobile: string;
}
export interface CollectionCenterPublic {
    id: string;
    status: CenterStatus;
    ownerName: string;
    name: string;
    createdAt: bigint;
    email: string;
    address: string;
    phone: string;
}
export interface PatientPublic {
    id: string;
    age: bigint;
    status: SampleStatus;
    name: string;
    refDoctor: string;
    centerId: string;
    bookingDate: bigint;
    gender: Gender;
    testIds: Array<bigint>;
    mobile: string;
}
export interface PaymentPublic {
    id: bigint;
    status: PaymentStatus;
    date: bigint;
    invoiceNumber: string;
    centerId: string;
    notes: string;
    amount: bigint;
}
export interface Report {
    id: bigint;
    reportUrl: string;
    patientId: string;
    filename: string;
    centerId: string;
    uploadedAt: bigint;
}
export interface DashboardStats {
    todaysSamples: bigint;
    pendingReports: bigint;
    totalBookings: bigint;
    thisMonthRevenue: bigint;
}
export interface LabTest {
    id: bigint;
    mrpPrice: bigint;
    fastingRequired: boolean;
    name: string;
    sampleType: string;
    tubeType: string;
    reportTime: string;
    category: string;
    partnerPrice: bigint;
}
export interface Session {
    token: string;
    userId: string;
    createdAt: bigint;
    role: Role;
}
export type LoginResult = {
    __kind__: "ok";
    ok: Session;
} | {
    __kind__: "err";
    err: string;
};
export interface BillingStats {
    totalTests: bigint;
    totalCommission: bigint;
    lastPayment?: PaymentPublic;
}
export enum CenterStatus {
    active = "active",
    inactive = "inactive"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid"
}
export enum Role {
    admin = "admin",
    collectionCenter = "collectionCenter"
}
export enum SampleStatus {
    sampleReceived = "sampleReceived",
    sampleCollected = "sampleCollected",
    reportReady = "reportReady",
    processing = "processing"
}
export interface backendInterface {
    addCenter(token: string, id: string, name: string, ownerName: string, phone: string, email: string, address: string, password: string): Promise<boolean>;
    addPayment(token: string, centerId: string, amount: bigint, invoiceNumber: string, notes: string): Promise<bigint>;
    addTest(token: string, name: string, category: string, sampleType: string, tubeType: string, fastingRequired: boolean, reportTime: string, mrpPrice: bigint, partnerPrice: bigint): Promise<bigint>;
    bookPatient(token: string, req: BookPatientRequest): Promise<string>;
    deleteTest(token: string, id: bigint): Promise<boolean>;
    getAllPatients(token: string): Promise<Array<PatientPublic>>;
    getBillingStats(token: string, centerId: string): Promise<BillingStats>;
    getCenterById(token: string, id: string): Promise<CollectionCenterPublic | null>;
    getCenters(token: string): Promise<Array<CollectionCenterPublic>>;
    getDashboardStats(token: string): Promise<DashboardStats>;
    getMyCenter(token: string): Promise<CollectionCenterPublic | null>;
    getPatientByIdOrMobile(token: string, searchQuery: string): Promise<PatientPublic | null>;
    getPatientsByCenter(token: string): Promise<Array<PatientPublic>>;
    getPaymentsByCenter(token: string, centerId: string): Promise<Array<PaymentPublic>>;
    getReportsByCenter(token: string, centerId: string, dateFrom: bigint | null, dateTo: bigint | null): Promise<Array<Report>>;
    getReportsByPatient(token: string, patientId: string): Promise<Array<Report>>;
    getTestById(id: bigint): Promise<LabTest | null>;
    getTests(): Promise<Array<LabTest>>;
    login(userId: string, password: string): Promise<LoginResult>;
    logout(token: string): Promise<boolean>;
    markPaymentPaid(token: string, paymentId: bigint): Promise<boolean>;
    setCenterStatus(token: string, id: string, active: boolean): Promise<boolean>;
    updateCenter(token: string, id: string, name: string, ownerName: string, phone: string, email: string, address: string): Promise<boolean>;
    updateSampleStatus(token: string, patientId: string, status: SampleStatus): Promise<PatientPublic | null>;
    updateTest(token: string, test: LabTest): Promise<boolean>;
    uploadReport(token: string, patientId: string, filename: string, reportUrl: string): Promise<bigint>;
    validateSession(token: string): Promise<Session | null>;
}
import type { BillingStats as _BillingStats, BookPatientRequest as _BookPatientRequest, CenterStatus as _CenterStatus, CollectionCenterPublic as _CollectionCenterPublic, Gender as _Gender, LabTest as _LabTest, LoginResult as _LoginResult, PatientPublic as _PatientPublic, PaymentPublic as _PaymentPublic, PaymentStatus as _PaymentStatus, Role as _Role, SampleStatus as _SampleStatus, Session as _Session } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCenter(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addCenter(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCenter(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addPayment(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addTest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean, arg6: string, arg7: bigint, arg8: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async bookPatient(arg0: string, arg1: BookPatientRequest): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.bookPatient(arg0, to_candid_BookPatientRequest_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookPatient(arg0, to_candid_BookPatientRequest_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteTest(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTest(arg0, arg1);
            return result;
        }
    }
    async getAllPatients(arg0: string): Promise<Array<PatientPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBillingStats(arg0: string, arg1: string): Promise<BillingStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillingStats(arg0, arg1);
                return from_candid_BillingStats_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillingStats(arg0, arg1);
            return from_candid_BillingStats_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCenterById(arg0: string, arg1: string): Promise<CollectionCenterPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCenterById(arg0, arg1);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCenterById(arg0, arg1);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCenters(arg0: string): Promise<Array<CollectionCenterPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCenters(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCenters(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(arg0: string): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats(arg0);
            return result;
        }
    }
    async getMyCenter(arg0: string): Promise<CollectionCenterPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCenter(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCenter(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientByIdOrMobile(arg0: string, arg1: string): Promise<PatientPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientByIdOrMobile(arg0, arg1);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientByIdOrMobile(arg0, arg1);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientsByCenter(arg0: string): Promise<Array<PatientPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientsByCenter(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientsByCenter(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentsByCenter(arg0: string, arg1: string): Promise<Array<PaymentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByCenter(arg0, arg1);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByCenter(arg0, arg1);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportsByCenter(arg0: string, arg1: string, arg2: bigint | null, arg3: bigint | null): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsByCenter(arg0, arg1, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsByCenter(arg0, arg1, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async getReportsByPatient(arg0: string, arg1: string): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsByPatient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsByPatient(arg0, arg1);
            return result;
        }
    }
    async getTestById(arg0: bigint): Promise<LabTest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestById(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestById(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTests(): Promise<Array<LabTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTests();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_LoginResult_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_LoginResult_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async markPaymentPaid(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markPaymentPaid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPaymentPaid(arg0, arg1);
            return result;
        }
    }
    async setCenterStatus(arg0: string, arg1: string, arg2: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setCenterStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCenterStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCenter(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCenter(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCenter(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateSampleStatus(arg0: string, arg1: string, arg2: SampleStatus): Promise<PatientPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSampleStatus(arg0, arg1, to_candid_SampleStatus_n35(this._uploadFile, this._downloadFile, arg2));
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSampleStatus(arg0, arg1, to_candid_SampleStatus_n35(this._uploadFile, this._downloadFile, arg2));
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTest(arg0: string, arg1: LabTest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTest(arg0, arg1);
            return result;
        }
    }
    async uploadReport(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadReport(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadReport(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async validateSession(arg0: string): Promise<Session | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BillingStats_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillingStats): BillingStats {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_CenterStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CenterStatus): CenterStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_CollectionCenterPublic_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollectionCenterPublic): CollectionCenterPublic {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_PatientPublic_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientPublic): PatientPublic {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentPublic_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentPublic): PaymentPublic {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_SampleStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SampleStatus): SampleStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Session_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentPublic]): PaymentPublic | null {
    return value.length === 0 ? null : from_candid_PaymentPublic_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CollectionCenterPublic]): CollectionCenterPublic | null {
    return value.length === 0 ? null : from_candid_CollectionCenterPublic_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientPublic]): PatientPublic | null {
    return value.length === 0 ? null : from_candid_PatientPublic_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LabTest]): LabTest | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Session]): Session | null {
    return value.length === 0 ? null : from_candid_Session_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalTests: bigint;
    totalCommission: bigint;
    lastPayment: [] | [_PaymentPublic];
}): {
    totalTests: bigint;
    totalCommission: bigint;
    lastPayment?: PaymentPublic;
} {
    return {
        totalTests: value.totalTests,
        totalCommission: value.totalCommission,
        lastPayment: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.lastPayment))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PaymentStatus;
    date: bigint;
    invoiceNumber: string;
    centerId: string;
    notes: string;
    amount: bigint;
}): {
    id: bigint;
    status: PaymentStatus;
    date: bigint;
    invoiceNumber: string;
    centerId: string;
    notes: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n17(_uploadFile, _downloadFile, value.status),
        date: value.date,
        invoiceNumber: value.invoiceNumber,
        centerId: value.centerId,
        notes: value.notes,
        amount: value.amount
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _CenterStatus;
    ownerName: string;
    name: string;
    createdAt: bigint;
    email: string;
    address: string;
    phone: string;
}): {
    id: string;
    status: CenterStatus;
    ownerName: string;
    name: string;
    createdAt: bigint;
    email: string;
    address: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_CenterStatus_n22(_uploadFile, _downloadFile, value.status),
        ownerName: value.ownerName,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        address: value.address,
        phone: value.phone
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    userId: string;
    createdAt: bigint;
    role: _Role;
}): {
    token: string;
    userId: string;
    createdAt: bigint;
    role: Role;
} {
    return {
        token: value.token,
        userId: value.userId,
        createdAt: value.createdAt,
        role: from_candid_Role_n33(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    status: _SampleStatus;
    name: string;
    refDoctor: string;
    centerId: string;
    bookingDate: bigint;
    gender: _Gender;
    testIds: Array<bigint>;
    mobile: string;
}): {
    id: string;
    age: bigint;
    status: SampleStatus;
    name: string;
    refDoctor: string;
    centerId: string;
    bookingDate: bigint;
    gender: Gender;
    testIds: Array<bigint>;
    mobile: string;
} {
    return {
        id: value.id,
        age: value.age,
        status: from_candid_SampleStatus_n8(_uploadFile, _downloadFile, value.status),
        name: value.name,
        refDoctor: value.refDoctor,
        centerId: value.centerId,
        bookingDate: value.bookingDate,
        gender: from_candid_Gender_n10(_uploadFile, _downloadFile, value.gender),
        testIds: value.testIds,
        mobile: value.mobile
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): CenterStatus {
    return "active" in value ? CenterStatus.active : "inactive" in value ? CenterStatus.inactive : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Session;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Session;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Session_n31(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    collectionCenter: null;
}): Role {
    return "admin" in value ? Role.admin : "collectionCenter" in value ? Role.collectionCenter : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sampleReceived: null;
} | {
    sampleCollected: null;
} | {
    reportReady: null;
} | {
    processing: null;
}): SampleStatus {
    return "sampleReceived" in value ? SampleStatus.sampleReceived : "sampleCollected" in value ? SampleStatus.sampleCollected : "reportReady" in value ? SampleStatus.reportReady : "processing" in value ? SampleStatus.processing : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CollectionCenterPublic>): Array<CollectionCenterPublic> {
    return value.map((x)=>from_candid_CollectionCenterPublic_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentPublic>): Array<PaymentPublic> {
    return value.map((x)=>from_candid_PaymentPublic_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PatientPublic>): Array<PatientPublic> {
    return value.map((x)=>from_candid_PatientPublic_n6(_uploadFile, _downloadFile, x));
}
function to_candid_BookPatientRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookPatientRequest): _BookPatientRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SampleStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SampleStatus): _SampleStatus {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    name: string;
    refDoctor: string;
    gender: Gender;
    testIds: Array<bigint>;
    mobile: string;
}): {
    age: bigint;
    name: string;
    refDoctor: string;
    gender: _Gender;
    testIds: Array<bigint>;
    mobile: string;
} {
    return {
        age: value.age,
        name: value.name,
        refDoctor: value.refDoctor,
        gender: to_candid_Gender_n3(_uploadFile, _downloadFile, value.gender),
        testIds: value.testIds,
        mobile: value.mobile
    };
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SampleStatus): {
    sampleReceived: null;
} | {
    sampleCollected: null;
} | {
    reportReady: null;
} | {
    processing: null;
} {
    return value == SampleStatus.sampleReceived ? {
        sampleReceived: null
    } : value == SampleStatus.sampleCollected ? {
        sampleCollected: null
    } : value == SampleStatus.reportReady ? {
        reportReady: null
    } : value == SampleStatus.processing ? {
        processing: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
